# Generated by Django 5.2.7 on 2025-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_desk_api', '0002_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
