# Generated by Django 5.2.7 on 2025-10-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soft_desk_api', '0003_issue_description_issue_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default='placeholder description'),
            preserve_default=False,
        ),
    ]
